### ISSUE TITLE
termservice not starting / not listening on boot

### ISSUE THREAD

**Issue by saper** [nahanni/bhyve-windows-unattend-xml#1]
Hello, I have followed https://people.freebsd.org/~grehan/bhyve_uefi/windows_iso_repack.txt and https://people.freebsd.org/~grehan/bhyve_uefi/windows_install.txt using Windows 2016 Technology Preview 4 and I think it installed fine.

Unfortunately, once I am in cmd.exe I can see that terminal services are not running (not even enabled at boot):

``````
PS C:\Windows\system32> get-service termservice | format-list                  


Name                : termservice
DisplayName         : Remote Desktop Services
Status              : Stopped                                          
DependentServices   : {UmRdpService}                                    
ServicesDependedOn  : {RPCSS}                                     
CanPauseAndContinue : False                                       
CanShutdown         : False                                                    
CanStop             : False                                                    
ServiceType         : Win32ShareProcess                                        
                                         ````

``````

Even if I start it with `net start termservice` or `net start umrdpservice`, nothing is listening on port 3389.

It seems though that the firewall rule is active. Nothing obvious in the event log. Any ideas how to troubleshoot this?

**Comment by saper** [comment]
I have managed to connect to this VM using Xen and see the graphical console. The installation is incomplete - it asks for a product key and then continues bringing up the desktop.

**Comment by l-d-x** [comment]
You will need to put in the TP4 product key under:

`<specialize>  <Microsoft-Windows-Shell-Setup>   <ProductKey>XXXXX</ProductKey>`

A fix will come shortly, but use this workaround for the time being.

**Comment by l-d-x** [comment]
Fixed in https://github.com/nahanni/bhyve-windows-unattend-xml/commit/d3f8585f792e6f7dfa8907eee80cb4e5abb9e490

You'll need to set the ProductKey as available from Microsoft's site (https://technet.microsoft.com/en-us/library/mt126134.aspx)

**Comment by saper** [comment]
It is now really unattended, thanks!
